//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONHOC
    {
        public MONHOC()
        {
            this.KETQUAs = new HashSet<KETQUA>();
        }
    
        public string MaMH { get; set; }
        public string TenMonHoc { get; set; }
        public string MaKhoa { get; set; }
        public Nullable<int> SoTC { get; set; }
    
        public virtual ICollection<KETQUA> KETQUAs { get; set; }
        public virtual KHOA KHOA { get; set; }
    }
}
