//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANQUYEN
    {
        public PHANQUYEN()
        {
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public string MaQuyen { get; set; }
        public string LoaiQuyen { get; set; }
    
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
