//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public SINHVIEN()
        {
            this.KETQUAs = new HashSet<KETQUA>();
        }
    
        public string MaSV { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string MaLop { get; set; }
        public string Hinh { get; set; }
    
        public virtual ICollection<KETQUA> KETQUAs { get; set; }
        public virtual LOP LOP { get; set; }
    }
}
