//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP()
        {
            this.SINHVIENs = new HashSet<SINHVIEN>();
        }
    
        public string MaLop { get; set; }
        public string TenLop { get; set; }
        public string MaKhoaHoc { get; set; }
        public string MaKhoa { get; set; }
        public string MaCT { get; set; }
        public Nullable<int> SoThuTu { get; set; }
    
        public virtual CHUONGTRINH CHUONGTRINH { get; set; }
        public virtual KHOA KHOA { get; set; }
        public virtual KHOAHOC KHOAHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SINHVIEN> SINHVIENs { get; set; }
    }
}
